'use client';

import { Info, HelpCircle } from 'lucide-react';

export default function DocsRequests() {
  return (
    <div className="space-y-8 max-w-4xl font-sans text-slate-800">
      <section className="space-y-4">
        <h1 className="text-3xl font-extrabold tracking-tight text-[#0c1e13]">Requests</h1>
        <p className="text-sm text-[#4e5b52] leading-relaxed">
          The Pagination feature allows you to efficiently navigate through large sets of data, such
          as transactions, ensuring optimal performance and a seamless user experience. When
          retrieving lists of resources, Pagination divides the data into manageable chunks called
          "pages," allowing you to fetch only the necessary data at a time.
        </p>
      </section>

      {/* Endpoints & Methods */}
      <section className="space-y-4">
        <h2 className="text-lg font-extrabold text-[#0c1e13]">API Endpoint</h2>
        <ul className="list-disc list-inside text-xs text-[#5d6b60] space-y-1 pl-2">
          <li>
            Generate ID Endpoint:{' '}
            <code className="font-mono bg-[#f4f7f4] px-1.5 py-0.5 rounded text-emerald-600 font-bold">
              POST /api/request-id
            </code>
          </li>
        </ul>

        {/* GET method */}
        <div className="space-y-2">
          <h3 className="font-bold text-xs text-[#0c1e13]">GET Method</h3>
          <p className="text-[11px] text-[#5d6b60]">Purpose: Retrieve user profile information.</p>
          <div className="bg-[#24292e] rounded-xl overflow-hidden shadow-md border border-slate-700">
            <div className="bg-[#1f2428] border-b border-slate-700 px-4 py-1.5 flex justify-between items-center text-[10px] font-mono text-slate-400">
              <span>Make file</span>
            </div>
            <pre className="p-4 overflow-x-auto text-[11px] font-mono text-emerald-400 bg-[#1b1f23] leading-relaxed">
              {`GET /api/users/123 HTTP/1.1
Host: example.com
Authorization: Bearer <access_token>`}
            </pre>
          </div>
        </div>

        {/* PUT method */}
        <div className="space-y-2">
          <h3 className="font-bold text-xs text-[#0c1e13]">PUT Method</h3>
          <p className="text-[11px] text-[#5d6b60]">Purpose: Update user profile information.</p>
          <div className="bg-[#24292e] rounded-xl overflow-hidden shadow-md border border-slate-700">
            <div className="bg-[#1f2428] border-b border-slate-700 px-4 py-1.5 flex justify-between items-center text-[10px] font-mono text-slate-400">
              <span>Make file</span>
            </div>
            <pre className="p-4 overflow-x-auto text-[11px] font-mono text-emerald-400 bg-[#1b1f23] leading-relaxed">
              {`PUT /api/users/123 HTTP/1.1
Host: example.com
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}`}
            </pre>
          </div>
        </div>
      </section>

      {/* Payload & Response */}
      <section className="space-y-4">
        <h2 className="text-lg font-extrabold text-[#0c1e13]">Request Payload</h2>
        <p className="text-xs text-[#4e5b52]">
          <strong>Purpose:</strong> Indicates the purpose for which the ID is being requested.
          <br />
          <strong>Metadata:</strong> Additional Information related to the request (optional).
        </p>

        <div className="bg-[#24292e] rounded-xl overflow-hidden shadow-md border border-slate-700">
          <div className="bg-[#1f2428] border-b border-slate-700 px-4 py-1.5 flex justify-between items-center text-[10px] font-mono text-slate-400">
            <span>Make file</span>
          </div>
          <pre className="p-4 overflow-x-auto text-[11px] font-mono text-emerald-400 bg-[#1b1f23] leading-relaxed">
            {`{
  "purpose": "transaction_tracking",
  "metadata": {
    "transaction_id": "123456789",
    "user_id": "987654321"
  }
}`}
          </pre>
        </div>
      </section>

      {/* Response Structure */}
      <section className="space-y-4">
        <h2 className="text-lg font-extrabold text-[#0c1e13]">Response Structure</h2>
        <ul className="list-disc list-inside text-xs text-[#4e5b52] space-y-1.5 pl-2 leading-relaxed">
          <li>
            <strong>ID:</strong> Unique identifier generated by the API.
          </li>
          <li>
            <strong>Timestamp:</strong> Date and time when the ID was generated.
          </li>
          <li>
            <strong>Status Code:</strong> HTTP status code indicating the success or failure of the
            request.
          </li>
        </ul>

        <div className="bg-[#24292e] rounded-xl overflow-hidden shadow-md border border-slate-700">
          <div className="bg-[#1f2428] border-b border-slate-700 px-4 py-1.5 flex justify-between items-center text-[10px] font-mono text-slate-400">
            <span>Example Response</span>
          </div>
          <pre className="p-4 overflow-x-auto text-[11px] font-mono text-emerald-400 bg-[#1b1f23] leading-relaxed">
            {`{
  "id": "7f7bd729-5be5-4c2b-a20e-85d13816f672",
  "timestamp": "2024-02-09T12:34:56Z",
  "status": "success"
}`}
          </pre>
        </div>
      </section>
    </div>
  );
}
