name: Backend CI

on:
  pull_request:
    branches:
      - dev
      - main

  push:
    branches:
      - dev

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore

      - run: dotnet build --no-restore

      - run: dotnet test